"""QIF P5 system-atlas tests.

The atlas is one self-contained HTML file with an embedded copy of the
fixture, so three things can rot silently between suite runs: the embedded
blob can drift from the sibling fixture, the fixture can stop conforming to
the frozen fws_atlas/1 schema, and the loader can pick up a JavaScript syntax
error that renders the page blank. The suite catches all three.

The loader tests shell out to node (skipped when node is absent, the
tests/test_webui_browser.py precedent) and evaluate only the block between
the ATLAS-CORE markers, which carries no DOM.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import textwrap
from pathlib import Path

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ATLAS_DIR = PROJECT_ROOT / "docs" / "qif" / "atlas"
ATLAS_HTML = ATLAS_DIR / "atlas.html"
FIXTURE = ATLAS_DIR / "fixture_llama7b_tp2.json"
PD_ATLAS = ATLAS_DIR / "pd_llama7b.json"
SCHEMA_MD = ATLAS_DIR / "SCHEMA.md"

# The PD pair the shipped document is (P5.4, D16). It is generated by the same
# command its provenance block prints, so the regenerate-and-compare test below
# and the file itself can never drift apart silently.
PD_ARGS = dict(
    # Absolute, so the test does not depend on the caller's working directory.
    # The tool prints the repo-relative spelling back into provenance, so the
    # emitted bytes are the same either way.
    hardware_config=str(PROJECT_ROOT / "configs/hardware-config/fws_cim_llama7b_mapped.yaml"),
    model_config=str(PROJECT_ROOT / "configs/model-config/llama2_7b_fws_inf.yaml"),
    prefill_layers_per_chip=8,
    decode_layers_per_chip=4,
    prefill_shared_chiplets=2,
    decode_shared_chiplets=1,
    decode_window=4,
    priced=True,
    label="Llama2-7B",
)

CORE_START = "// ==ATLAS-CORE-START=="
CORE_END = "// ==ATLAS-CORE-END=="
EMBED_RE = re.compile(
    r'<script[^>]*type="application/json"[^>]*id="atlas-embedded"[^>]*>(.*?)</script>',
    re.DOTALL,
)


def _html() -> str:
    return ATLAS_HTML.read_text(encoding="utf-8")


def _fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def _node() -> str:
    node = shutil.which("node")
    if node is None:
        pytest.skip("node is not installed; the atlas loader tests need it")
    return node


def _run_core(driver: str, tmp_path: Path, document: Path = FIXTURE) -> str:
    """Evaluate the ATLAS core block headlessly and run a driver against it.

    ``document`` defaults to the P5 fixture; P3's export tests pass their own
    emitted document so the SAME loader judges both (tests/test_qif_mapping.py).
    """
    html = _html()
    core = html[html.index(CORE_START) : html.index(CORE_END)]
    script = tmp_path / "driver.js"
    script.write_text(
        "const fs = require('fs');\n"
        "const doc = JSON.parse(fs.readFileSync(%r, 'utf8'));\n" % str(document)
        + "const ATLAS = eval('(function(){' + "
        + json.dumps(core)
        + " + '; return ATLAS; })()');\n"
        + textwrap.dedent(driver),
        encoding="utf-8",
    )
    result = subprocess.run(
        [_node(), str(script)],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=str(PROJECT_ROOT),
    )
    assert result.returncode == 0, result.stderr
    return result.stdout.strip()


# --- P5.1 the fixture -------------------------------------------------------


def test_fixture_is_an_fws_atlas_1_document():
    doc = _fixture()
    assert doc["schema"] == "fws_atlas/1"
    for key in ("title", "provenance", "cards"):
        assert key in doc, key
    for key in ("systems", "chips", "macros", "tiles", "links", "metrics", "relaxations"):
        assert isinstance(doc[key], list) and doc[key], key
    provenance = doc["provenance"]
    assert provenance["authored"] and provenance["author"]
    assert isinstance(provenance["invented_fields"], list)


def test_fixture_declares_no_accuracy_field_anywhere():
    # D23 is hard: this is a performance model. The schema has no accuracy
    # field and no document may smuggle one in under another name.
    banned = ("accuracy", "perplexity", "top1", "top_1", "bleu", "error_rate")
    blob = FIXTURE.read_text(encoding="utf-8").lower()
    for word in banned:
        assert word not in blob, word


def test_embedded_blob_is_the_fixture_verbatim():
    # SCHEMA.md's own instruction is "when the fixture changes, re-embed it".
    # A stale embed is a document that draws the wrong mapping under the
    # right title, which is exactly the silent divergence the note warns of.
    match = EMBED_RE.search(_html())
    assert match is not None, "atlas.html carries no atlas-embedded blob"
    assert json.loads(match.group(1)) == _fixture()


# --- P5.3 the loader --------------------------------------------------------


def test_the_whole_inline_script_parses(tmp_path):
    # A syntax error anywhere in atlas.html renders the deliverable blank with
    # nothing else to notice it: the page is one file and there is no build.
    html = _html()
    start = html.index(CORE_START)
    open_tag = html.rindex("<script>", 0, start)
    end_tag = html.index("</script>", start)
    script = tmp_path / "atlas_inline.js"
    script.write_text(html[open_tag + len("<script>") : end_tag], encoding="utf-8")
    result = subprocess.run(
        [_node(), "--check", str(script)], capture_output=True, text=True, timeout=60
    )
    assert result.returncode == 0, result.stderr


def test_loader_parses_and_the_fixture_validates_clean(tmp_path):
    out = _run_core(
        """
        const v = ATLAS.validate(doc);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          warnings: v.warnings.map(w => w.rule + ' ' + w.field),
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["errors"] == []
    assert report["warnings"] == []


def test_self_test_corrupts_once_per_rule_and_every_refusal_fires(tmp_path):
    out = _run_core(
        """
        const rows = ATLAS.selfTest(doc);
        console.log(JSON.stringify({
          total: rows.length,
          cases: ATLAS.CORRUPTIONS.length,
          failed: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what),
          skipped: rows.filter(r => r.skipped).map(r => r.rule + ' ' + r.what),
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["failed"] == []
    # The clean document plus exactly one case per corruption.
    assert report["total"] == report["cases"] + 1
    # A skip is honest ("this document gives the harness no way to build that
    # corruption") but it proves nothing, so the set of them is PINNED: only the
    # two PD rules, which need a second system this one-system fixture has not
    # got. The PD document below fires exactly those.
    assert sorted(report["skipped"]) == [
        "R28 a metric in a two-system document says whose figure it is",
        "R29 a PD document loses the handoff that couples its two systems",
    ]


def test_the_shipped_documents_between_them_fire_every_corruption(tmp_path):
    """No rule may be skipped by EVERY document we ship.

    A corruption that is not constructible anywhere is a rule nothing exercises,
    which is how a refusal quietly stops working.
    """
    fired = set()
    total = None
    for document in (FIXTURE, PD_ATLAS):
        out = _run_core(
            """
            const rows = ATLAS.selfTest(doc);
            console.log(JSON.stringify({
              cases: ATLAS.CORRUPTIONS.length,
              fired: rows.filter(r => !r.skipped && r.rule !== 'R0').map(r => r.rule + ' ' + r.what),
              failed: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what),
            }));
            """,
            tmp_path,
            document=document,
        )
        report = json.loads(out)
        assert report["failed"] == [], (document.name, report["failed"])
        fired.update(report["fired"])
        total = report["cases"]
    assert len(fired) == total, sorted(fired)


def test_every_rule_the_loader_can_emit_is_documented_in_schema_md(tmp_path):
    # The refusal panel tells the reader "See SCHEMA.md for the rule numbers",
    # so a rule id that fires but is undocumented sends the reader nowhere.
    out = _run_core(
        """
        console.log(JSON.stringify(Array.from(new Set(ATLAS.CORRUPTIONS.map(c => c.rule))).sort()));
        """,
        tmp_path,
    )
    rules = json.loads(out)
    html = _html()
    emitted = set(re.findall(r'[EW]\("(R\d+)"', html))
    assert emitted <= set(rules), sorted(emitted - set(rules))
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    documented = set(re.findall(r"^\| (\d+) \|", schema, re.MULTILINE))
    missing = sorted(int(r[1:]) for r in emitted if r[1:] not in documented)
    assert not missing, "rules missing from SCHEMA.md: %s" % missing


def test_schema_md_states_the_self_tests_real_case_count(tmp_path):
    """WAVE C AUDIT: SCHEMA.md said 34 cases while the harness ran 37.

    SCHEMA.md is the frozen fws_atlas/1 contract and the copy a reader trusts,
    and the rule-coverage test above never checked the COUNT -- only that each
    rule id appears in the table. This asserts the integer in the prose equals
    what selfTest actually returns, so the sentence cannot rot again.
    """
    out = _run_core("console.log(ATLAS.selfTest(doc).length);", tmp_path)
    rows = int(out)
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    stated = re.search(r"It runs (\d+)\s*\ncases:", schema)
    assert stated, "SCHEMA.md no longer states a self-test case count"
    assert int(stated.group(1)) == rows


@pytest.mark.parametrize(
    "rule,field,mutation",
    [
        ("R1", "provenance", "delete d.provenance;"),
        ("R24", "cards.ctt_4k_1024x4.slicing", "d.cards.ctt_4k_1024x4.slicing = true;"),
        ("R25", "slice", "d.tiles[0].slice = {index: 9, of: 2, bits: 4};"),
        ("R26", "role", 'd.systems[0].role = "mixed";'),
        ("R27", "duty_cycle", "d.macros[0].duty_cycle = 5.0;"),
        ("R6", "basis", 'd.links[0].basis = "";'),
        ("R18", "value", 'd.metrics[0].value = "lots";'),
    ],
)
def test_declared_schema_rules_are_enforced_not_just_documented(rule, field, mutation, tmp_path):
    out = _run_core(
        """
        const d = JSON.parse(JSON.stringify(doc));
        %s
        const v = ATLAS.validate(d);
        console.log(JSON.stringify(v.errors.map(e => e.rule + ' ' + e.field)));
        """
        % mutation,
        tmp_path,
    )
    hits = [e for e in json.loads(out) if e.startswith(rule + " ") and field in e]
    assert hits, json.loads(out)


# --- P5.4 duty cycle, and the PD two-system document (D16) ------------------

def _shipped_documents():
    """Every fws_atlas/1 document in docs/qif/atlas/, found by SCHEMA ID.

    WAVE C AUDIT: this was a hand-maintained tuple, and qwen3_5_4b.json shipped
    into the same directory without being added to it -- so the view-rule sweep
    and the D23 scan below, which both claim to cover "every shipped document",
    silently skipped one. Globbing by the schema id means a document another
    workstream lands is covered the moment it exists, with nobody to remember.
    """
    found = []
    for path in sorted(ATLAS_DIR.glob("*.json")):
        try:
            blob = json.loads(path.read_text(encoding="utf-8"))
        except (ValueError, UnicodeDecodeError):
            continue
        if isinstance(blob, dict) and blob.get("schema") == "fws_atlas/1":
            found.append(path.name)
    return tuple(found)


SHIPPED = _shipped_documents()


def test_the_pd_document_is_a_two_system_machine_with_one_handoff():
    """D16 drawn: two inventories, two roles, one priced handoff between them."""
    assert PD_ATLAS.exists(), (
        "docs/qif/atlas/pd_llama7b.json is the P5.4 PD artifact and is committed; "
        "regenerate it with the command in its provenance block"
    )
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    assert doc["schema"] == "fws_atlas/1"
    assert [system["role"] for system in doc["systems"]] == ["prefill", "decode"]
    assert [system["phase"] for system in doc["systems"]] == ["prefill", "decode"]
    chip_system = {chip["id"]: chip["system"] for chip in doc["chips"]}
    handoff = [link for link in doc["links"] if link["role"] == "pd"]
    assert len(handoff) == 1
    assert chip_system[handoff[0]["from"]] != chip_system[handoff[0]["to"]]
    assert handoff[0]["bytes"] > 0 and handoff[0]["per"] and handoff[0]["basis"]
    # Two INVENTORIES, not two halves of one: each system holds its own chips.
    for system in doc["systems"]:
        assert any(chip["system"] == system["id"] for chip in doc["chips"])


def test_the_pd_document_prices_each_half_on_its_own_timeline():
    """P4 duty cycles and metrics per SYSTEM (P5.4). One evaluation shared
    between the halves would print a single measurement twice."""
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    chip_system = {chip["id"]: chip["system"] for chip in doc["chips"]}
    duty = {"sys.prefill": [], "sys.decode": []}
    for macro in doc["macros"]:
        value = macro.get("duty_cycle")
        if value is not None:
            duty[chip_system[macro["chip"]]].append(value)
    assert duty["sys.prefill"] and duty["sys.decode"]
    assert all(0.0 <= v <= 1.0 for values in duty.values() for v in values)
    # The two timelines are different machines, so their duty cycles differ.
    assert max(duty["sys.prefill"]) != max(duty["sys.decode"])
    keys = [metric["key"] for metric in doc["metrics"]]
    assert any(key.startswith("sys.prefill.") for key in keys)
    assert any(key.startswith("sys.decode.") for key in keys)
    # The headline label is published twice — once per system — which is exactly
    # why R28 requires every metric to name its system.
    headline = [m for m in doc["metrics"] if m["key"].endswith(".tokens_per_s")]
    assert len(headline) == 2
    assert headline[0]["label"] == headline[1]["label"]
    assert headline[0]["key"] != headline[1]["key"]


def test_the_pd_document_discloses_what_two_inventories_mean():
    """The two facts a PD reader cannot infer from the picture (D21)."""
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    by_key = {item["constraint"]: item for item in doc["relaxations"]}
    assert "pd_each_half_maps_the_whole_model" in by_key
    assert "pd_each_half_prices_the_whole_request" in by_key
    # One entry per constraint key, even though two systems disclose them.
    keys = [item["constraint"] for item in doc["relaxations"]]
    assert len(keys) == len(set(keys)), keys
    # A constraint the halves disclose DIFFERENTLY names both of them rather
    # than silently keeping one.
    window = by_key["decode_series_window"]["value"]
    assert "sys.prefill" in window and "sys.decode" in window


def test_the_pd_document_validates_clean_through_the_real_loader(tmp_path):
    out = _run_core(
        """
        const v = ATLAS.validate(doc);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          warnings: v.warnings.map(w => w.rule + ' ' + w.field),
        }));
        """,
        tmp_path,
        document=PD_ATLAS,
    )
    report = json.loads(out)
    assert report["errors"] == []
    assert report["warnings"] == []


def test_the_pd_document_is_what_a_fresh_run_produces(tmp_path):
    """Regenerate and compare BYTES: a stale artifact is a wrong picture under
    a right title, the same gate p3_llama7b_tp2.json and the Granite atlas have."""
    import tools.fws_emit_atlas as emit
    import fws_atlas_export

    _pair, _rows, document = emit.build_pd(**PD_ARGS)
    regenerated = fws_atlas_export.write_atlas_json(document, tmp_path / "pd.json")
    assert regenerated == PD_ATLAS.read_text(encoding="utf-8"), (
        "docs/qif/atlas/pd_llama7b.json is stale; regenerate it with the command "
        "in its provenance block"
    )


def test_the_unpriced_pd_path_builds_a_clean_document_and_claims_less(tmp_path):
    """WAVE C AUDIT: `--pd` without `--priced` is advertised and was untested.

    The module docstring documents the combination and every PD test above sets
    priced=True, so this branch had never been run by the suite. Two things it
    must get right: the document still passes the real loader, and it discloses
    LESS -- an unpriced document lowers no request, so the whole-REQUEST claim
    has nothing to be about and must not appear beside the whole-MODEL one.
    """
    import tools.fws_emit_atlas as emit
    import fws_atlas_export

    args = dict(PD_ARGS)
    args["priced"] = False
    _pair, _rows, document = emit.build_pd(**args)
    path = tmp_path / "pd_unpriced.json"
    fws_atlas_export.write_atlas_json(document, path)

    constraints = {item["constraint"] for item in document["relaxations"]}
    assert "pd_each_half_maps_the_whole_model" in constraints
    assert "pd_each_half_prices_the_whole_request" not in constraints
    assert all(macro.get("duty_cycle") is None for macro in document["macros"])

    out = _run_core(
        """
        const v = ATLAS.validate(doc);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          warnings: v.warnings.map(w => w.rule + ' ' + w.field),
        }));
        """,
        tmp_path,
        document=path,
    )
    report = json.loads(out)
    assert report["errors"] == [] and report["warnings"] == []


def test_the_pd_command_in_the_provenance_block_is_the_one_that_made_it():
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    command = doc["provenance"]["reference_run"]["command"]
    assert command.startswith("tools/fws_emit_atlas.py --pd ")
    assert "--priced" in command
    for flag, value in (
        ("--pd_prefill_layers_per_chip", PD_ARGS["prefill_layers_per_chip"]),
        ("--pd_decode_layers_per_chip", PD_ARGS["decode_layers_per_chip"]),
        ("--pd_prefill_shared_chiplets", PD_ARGS["prefill_shared_chiplets"]),
        ("--pd_decode_shared_chiplets", PD_ARGS["decode_shared_chiplets"]),
        ("--pd_decode_window", PD_ARGS["decode_window"]),
    ):
        assert "%s %s" % (flag, value) in command, flag


def test_no_shipped_document_smuggles_an_accuracy_field(tmp_path):
    # D23 is hard, and it applies to every artifact in this directory.
    banned = ("accuracy", "perplexity", "top1", "top_1", "bleu", "error_rate")
    for name in SHIPPED:
        blob = (ATLAS_DIR / name).read_text(encoding="utf-8").lower()
        for word in banned:
            assert word not in blob, (name, word)


# --- P5.4 / P5.5 the view rules ---------------------------------------------


@pytest.mark.parametrize("name", SHIPPED)
def test_the_view_rules_hold_on_every_shipped_document(name, tmp_path):
    """The renderer's own encoding law, asserted document by document."""
    out = _run_core(
        """
        const rows = ATLAS.viewTest(doc);
        console.log(JSON.stringify({
          total: rows.length,
          broken: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what + ' :: ' + r.got),
        }));
        """,
        tmp_path,
        document=ATLAS_DIR / name,
    )
    report = json.loads(out)
    assert report["broken"] == []
    assert report["total"] >= 9


def test_every_view_rule_the_renderer_asserts_is_documented_in_schema_md(tmp_path):
    # The same gate the refusals have: a rule the panel prints and SCHEMA.md
    # does not carry sends the reader nowhere.
    out = _run_core(
        """
        console.log(JSON.stringify(ATLAS.viewTest(doc).map(r => r.rule)));
        """,
        tmp_path,
    )
    rules = json.loads(out)
    assert len(rules) == len(set(rules)), rules
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    documented = set(re.findall(r"^\| (V\d+) \|", schema, re.MULTILINE))
    assert set(rules) <= documented, sorted(set(rules) - documented)


def test_the_duty_channel_is_its_own_ink_and_never_a_group_hue(tmp_path):
    out = _run_core(
        """
        console.log(JSON.stringify({
          duty: ATLAS.DUTY_INK,
          hues: ATLAS.HUES,
          extreme: ATLAS.dutyExtreme(doc),
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["duty"] not in report["hues"]
    # The fixture declares duty cycles, so the legend has a busiest macro to name.
    assert report["extreme"] and 0.0 <= report["extreme"]["value"] <= 1.0


def test_a_filter_changes_the_picture_and_never_a_figure(tmp_path):
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        const before = JSON.stringify({m: doc.metrics, h: ATLAS.hueMap(doc)});
        const f = ATLAS.emptyFilter();
        f.q = 'lm_head';
        const selected = doc.macros.filter(m => ATLAS.macroMatches(doc, ix, m, f)).length;
        const after = JSON.stringify({m: doc.metrics, h: ATLAS.hueMap(doc)});
        console.log(JSON.stringify({same: before === after, selected: selected, all: doc.macros.length}));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["same"], "a filter moved a metric or repainted a group"
    assert 0 < report["selected"] < report["all"], report


def test_owner_search_indexes_owners_and_not_measurements(tmp_path):
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        const measured = doc.macros.find(m => typeof m.duty_cycle === 'number' && String(m.duty_cycle).indexOf('.') > 0);
        const byValue = ATLAS.emptyFilter(); byValue.q = String(measured.duty_cycle);
        const byOwner = ATLAS.emptyFilter(); byOwner.q = doc.tiles[0].owner.block;
        console.log(JSON.stringify({
          needle: String(measured.duty_cycle),
          byValue: doc.macros.filter(m => ATLAS.macroMatches(doc, ix, m, byValue)).length,
          byOwner: doc.macros.filter(m => ATLAS.macroMatches(doc, ix, m, byOwner)).length,
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["byValue"] == 0, report
    assert report["byOwner"] > 0, report


def test_a_column_map_bracket_never_spans_two_weight_matrices(tmp_path):
    """D11: a bit-sliced group shares a bracket — and shares it with nothing else."""
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        let brackets = 0, chained = 0, bad = [];
        doc.macros.forEach(m => {
          ATLAS.bracketsFor(doc, ix, m).forEach(b => {
            brackets++;
            if (b.chained.length) chained++;
            const owners = new Set(b.tiles.map(id => ATLAS.ownerKey(ix.tile[id])));
            if (owners.size !== 1) bad.push(m.id + ' ' + b.key);
            b.tiles.forEach(id => {
              const t = ix.tile[id];
              if (t.columns.start < b.start || t.columns.start + t.columns.count > b.end) {
                bad.push(m.id + ' span ' + id);
              }
              if (b.chained.indexOf(t.macro) >= 0) bad.push(m.id + ' chained-to-itself');
            });
          });
        });
        console.log(JSON.stringify({brackets: brackets, chained: chained, bad: bad.slice(0, 5)}));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["bad"] == []
    assert report["brackets"] > 0
    # The fixture's weight matrices chain across macros, which is the D11
    # question the column map exists to answer.
    assert report["chained"] > 0


def test_breadcrumbs_are_containment_and_the_draw_budget_is_applied(tmp_path):
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        const macro = doc.macros.find(m => (m.tiles || []).length);
        const path = ATLAS.crumbs(doc, ix, 'macro', null, macro.id);
        const fat = JSON.parse(JSON.stringify(doc.chips[0]));
        for (let i = 0; i <= ATLAS.DRAW_BUDGET; i++) fat.macros.push('ghost.mac.' + i);
        fat.capacity.macro_slots = fat.macros.length;
        const real = ix.chip[macro.chip];   // a chip that actually holds tiles
        console.log(JSON.stringify({
          levels: path.map(c => c.level),
          chip: path[1].id === macro.chip,
          system: ix.chip[macro.chip].system === ix.sys[ix.chip[macro.chip].system].id,
          budget: ATLAS.DRAW_BUDGET,
          fatDrawn: ATLAS.chipDrawable(doc, fat),
          realDrawn: doc.chips.every(c => ATLAS.chipDrawable(doc, c)),
          slots: (real.capacity || {}).macro_slots,
          rectsDuty: ATLAS.chipRects(doc, real, true),
          rectsPlain: ATLAS.chipRects(doc, real, false),
          pkg: ATLAS.drawnRects(doc, 'package', null, null, false),
          chips: doc.chips.length,
          macroRects: ATLAS.macroRects(macro, false),
          tiles: (macro.tiles || []).length,
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["levels"] == ["package", "chip", "macro"]
    assert report["chip"] and report["system"]
    assert report["budget"] == 10000
    assert report["fatDrawn"] is False and report["realDrawn"] is True
    # WAVE C AUDIT: the budget is stated in RECTS, so it must be COUNTED in
    # rects. It used to be enforced against capacity.macro_slots, which is a
    # different and much smaller quantity -- a chip that passed the slot check
    # could still emit five times the budget. These assertions pin the unit.
    assert report["rectsDuty"] > report["slots"]
    assert report["rectsPlain"] > report["slots"]
    assert report["rectsDuty"] == report["rectsPlain"] + 2 * report["slots"]
    assert report["pkg"] > report["chips"]          # a chip is not one rect
    assert report["macroRects"] == report["tiles"] + 1  # the track plus a band each


def test_every_metric_in_the_pd_document_names_its_system(tmp_path):
    out = _run_core(
        """
        const named = doc.metrics.map(m => ATLAS.metricSystem(doc, m));
        console.log(JSON.stringify({
          orphans: doc.metrics.filter((m, i) => named[i] == null).map(m => m.key),
          systems: Array.from(new Set(named)).sort(),
        }));
        """,
        tmp_path,
        document=PD_ATLAS,
    )
    report = json.loads(out)
    assert report["orphans"] == []
    assert report["systems"] == ["sys.decode", "sys.prefill"]


def test_schema_md_documents_the_contract_the_renderer_now_reads():
    """The Wave B audit caught SCHEMA.md omitting fields the renderer used.

    Every field, channel and query parameter added in P5.4/P5.5 is named here,
    so the contract and the page cannot drift apart again.
    """
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    for token in (
        "`system` | string",          # metrics[].system
        "`duty_cycle` | number \\| null",
        "?data=<file>",
        "?duty=1",
        "?view=package",
        "`?macro=<macro id>`",
        "Bar on the macro's top edge",
        "Bracket over a column span",
        "Dimming",
        "pd_llama7b.json",
        "absolute 0–1 scale",
    ):
        assert token in schema, token


def test_the_sibling_fetch_never_silently_replaces_an_embedded_document():
    """The boot block is the one part of the page no headless run reaches.

    It touches location, document, fetch and the live state object, so this is
    a SOURCE-level assertion and says so: the fetch must be conditional on
    ?data= or on there being no embedded blob. It used to fire unconditionally
    and race the page — whoever embedded a document in this file meant it to be
    the one on screen, and the late fetch would swap it for whatever else
    happens to sit in the directory.
    """
    html = _html()
    assert 'var target = wanted || (embedded ? null : "fixture_llama7b_tp2.json");' in html
    assert 'if (target && typeof fetch === "function") {' in html
    # The unconditional form is gone, not merely guarded downstream.
    assert 'fetch(wanted || "fixture_llama7b_tp2.json"' not in html
    # And a dropped or picked document still outranks an in-flight fetch.
    assert 'S.source === "embedded blob" || S.source === "none"' in html
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    assert "the sibling fetch runs only when this parameter asks for one" in schema


def test_the_quotient_scan_covers_every_placement_table():
    """R9 reads the placement tables too, not just the document root.

    A half-ported area-division producer would put per-chip arithmetic exactly
    there, and the self-test proves it by corrupting a macros[] row.
    """
    html = _html()
    assert '["macros", "tiles", "links", "metrics"].forEach(function (k) {' in html
    assert "d.macros[0].arrays_per_chip = 3.7" in html


def test_a_bit_sliced_group_shares_one_bracket(tmp_path):
    """D11's own sentence, drawn: no shipped card slices today, so the case is
    built on a copy of the fixture — two tiles of ONE weight matrix on ONE
    macro, each carrying a slice role."""
    out = _run_core(
        """
        const d = JSON.parse(JSON.stringify(doc));
        const macro = d.macros.find(m => (m.tiles || []).length >= 2);
        const card = d.cards[macro.card];
        card.bits_per_cell = 4;
        card.slicing = true;                       // 4 < weight_bits, ADJ-4
        const tiles = macro.tiles.map(id => d.tiles.find(t => t.id === id));
        tiles[1].owner = JSON.parse(JSON.stringify(tiles[0].owner));
        tiles.forEach((t, i) => { t.slice = {index: i, of: tiles.length, bits: 4}; });
        const v = ATLAS.validate(d);
        const ix = ATLAS.makeIndex(d);
        const brackets = ATLAS.bracketsFor(d, ix, macro);
        const mine = brackets.filter(b => b.tiles.length === tiles.length);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          kinds: brackets.map(b => b.kind),
          label: mine.length ? mine[0].label : null,
          owners: mine.length ? Array.from(new Set(mine[0].tiles.map(id => ATLAS.ownerKey(ix.tile[id])))).length : 0,
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["errors"] == [], report["errors"]
    assert "slice" in report["kinds"]
    assert "bit slices (D11)" in report["label"]
    assert report["owners"] == 1
