"""QIF P5 system-atlas tests.

The atlas is one self-contained HTML file with an embedded copy of the
fixture, so three things can rot silently between suite runs: the embedded
blob can drift from the sibling fixture, the fixture can stop conforming to
the frozen fws_atlas/1 schema, and the loader can pick up a JavaScript syntax
error that renders the page blank. The suite catches all three.

The loader tests shell out to node (skipped when node is absent, the
tests/test_webui_browser.py precedent) and evaluate only the block between
the ATLAS-CORE markers, which carries no DOM.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import textwrap
from pathlib import Path

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ATLAS_DIR = PROJECT_ROOT / "docs" / "qif" / "atlas"
ATLAS_HTML = ATLAS_DIR / "atlas.html"
FIXTURE = ATLAS_DIR / "fixture_llama7b_tp2.json"
PD_ATLAS = ATLAS_DIR / "pd_llama7b.json"
SCHEMA_MD = ATLAS_DIR / "SCHEMA.md"

# The PD pair the shipped document is (P5.4, D16). It is generated by the same
# command its provenance block prints, so the regenerate-and-compare test below
# and the file itself can never drift apart silently.
PD_ARGS = dict(
    # Absolute, so the test does not depend on the caller's working directory.
    # The tool prints the repo-relative spelling back into provenance, so the
    # emitted bytes are the same either way.
    hardware_config=str(PROJECT_ROOT / "configs/hardware-config/fws_cim_llama7b_mapped.yaml"),
    model_config=str(PROJECT_ROOT / "configs/model-config/llama2_7b_fws_inf.yaml"),
    prefill_layers_per_chip=8,
    decode_layers_per_chip=4,
    prefill_shared_chiplets=2,
    decode_shared_chiplets=1,
    decode_window=4,
    priced=True,
    label="Llama2-7B",
)

CORE_START = "// ==ATLAS-CORE-START=="
CORE_END = "// ==ATLAS-CORE-END=="
EMBED_RE = re.compile(
    r'<script[^>]*type="application/json"[^>]*id="atlas-embedded"[^>]*>(.*?)</script>',
    re.DOTALL,
)


def _html() -> str:
    return ATLAS_HTML.read_text(encoding="utf-8")


def _fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def _node() -> str:
    node = shutil.which("node")
    if node is None:
        pytest.skip("node is not installed; the atlas loader tests need it")
    return node


def _run_core(driver: str, tmp_path: Path, document: Path = FIXTURE) -> str:
    """Evaluate the ATLAS core block headlessly and run a driver against it.

    ``document`` defaults to the P5 fixture; P3's export tests pass their own
    emitted document so the SAME loader judges both (tests/test_qif_mapping.py).
    """
    html = _html()
    core = html[html.index(CORE_START) : html.index(CORE_END)]
    script = tmp_path / "driver.js"
    script.write_text(
        "const fs = require('fs');\n"
        "const doc = JSON.parse(fs.readFileSync(%r, 'utf8'));\n" % str(document)
        + "const ATLAS = eval('(function(){' + "
        + json.dumps(core)
        + " + '; return ATLAS; })()');\n"
        + textwrap.dedent(driver),
        encoding="utf-8",
    )
    result = subprocess.run(
        [_node(), str(script)],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=str(PROJECT_ROOT),
    )
    assert result.returncode == 0, result.stderr
    return result.stdout.strip()


# --- P5.1 the fixture -------------------------------------------------------


def test_fixture_is_an_fws_atlas_1_document():
    doc = _fixture()
    assert doc["schema"] == "fws_atlas/1"
    for key in ("title", "provenance", "cards"):
        assert key in doc, key
    for key in ("systems", "chips", "macros", "tiles", "links", "metrics", "relaxations"):
        assert isinstance(doc[key], list) and doc[key], key
    provenance = doc["provenance"]
    assert provenance["authored"] and provenance["author"]
    assert isinstance(provenance["invented_fields"], list)


def test_fixture_declares_no_accuracy_field_anywhere():
    # D23 is hard: this is a performance model. The schema has no accuracy
    # field and no document may smuggle one in under another name.
    banned = ("accuracy", "perplexity", "top1", "top_1", "bleu", "error_rate")
    blob = FIXTURE.read_text(encoding="utf-8").lower()
    for word in banned:
        assert word not in blob, word


def test_the_page_embeds_no_fixture_and_fetches_the_real_artifacts():
    # THE PAGE IS THE RESULTS PAGE NOW, and it draws the checked-in artifacts of
    # its own directory. It used to open on an EMBEDDED hand-authored fixture,
    # which meant the first thing a reader saw was a different machine, under a
    # confusingly similar title, from the numbers every other page reported.
    # An embedded document is a stale document the moment the artifacts move,
    # so there is none: both blobs are null and the page fetches.
    html = _html()
    for name, pattern in (("atlas", EMBED_RE), ("frontier", FRONT_EMBED_RE)):
        match = pattern.search(html)
        assert match is not None, f"atlas.html carries no {name}-embedded slot"
        assert json.loads(match.group(1)) is None, (
            f"the {name} slot embeds a document again; the page must fetch the "
            "artifacts so it can never show a stale machine"
        )
    for artifact in ("_report.json", "../dse/", ".json"):
        assert artifact in html, artifact


# --- P5.3 the loader --------------------------------------------------------


def test_the_whole_inline_script_parses(tmp_path):
    # A syntax error anywhere in atlas.html renders the deliverable blank with
    # nothing else to notice it: the page is one file and there is no build.
    html = _html()
    start = html.index(CORE_START)
    open_tag = html.rindex("<script>", 0, start)
    end_tag = html.index("</script>", start)
    script = tmp_path / "atlas_inline.js"
    script.write_text(html[open_tag + len("<script>") : end_tag], encoding="utf-8")
    result = subprocess.run(
        [_node(), "--check", str(script)], capture_output=True, text=True, timeout=60
    )
    assert result.returncode == 0, result.stderr


def test_loader_parses_and_the_fixture_validates_clean(tmp_path):
    out = _run_core(
        """
        const v = ATLAS.validate(doc);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          warnings: v.warnings.map(w => w.rule + ' ' + w.field),
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["errors"] == []
    assert report["warnings"] == []


def test_self_test_corrupts_once_per_rule_and_every_refusal_fires(tmp_path):
    out = _run_core(
        """
        const rows = ATLAS.selfTest(doc);
        console.log(JSON.stringify({
          total: rows.length,
          cases: ATLAS.CORRUPTIONS.length,
          failed: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what),
          skipped: rows.filter(r => r.skipped).map(r => r.rule + ' ' + r.what),
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["failed"] == []
    # The clean document plus exactly one case per corruption.
    assert report["total"] == report["cases"] + 1
    # A skip is honest ("this document gives the harness no way to build that
    # corruption") but it proves nothing, so the set of them is PINNED: only the
    # two PD rules, which need a second system this one-system fixture has not
    # got. The PD document below fires exactly those.
    assert sorted(report["skipped"]) == [
        "R28 a metric in a two-system document says whose figure it is",
        "R29 a PD document loses the handoff that couples its two systems",
    ]


def test_the_shipped_documents_between_them_fire_every_corruption(tmp_path):
    """No rule may be skipped by EVERY document we ship.

    A corruption that is not constructible anywhere is a rule nothing exercises,
    which is how a refusal quietly stops working.
    """
    fired = set()
    total = None
    for document in (FIXTURE, PD_ATLAS):
        out = _run_core(
            """
            const rows = ATLAS.selfTest(doc);
            console.log(JSON.stringify({
              cases: ATLAS.CORRUPTIONS.length,
              fired: rows.filter(r => !r.skipped && r.rule !== 'R0').map(r => r.rule + ' ' + r.what),
              failed: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what),
            }));
            """,
            tmp_path,
            document=document,
        )
        report = json.loads(out)
        assert report["failed"] == [], (document.name, report["failed"])
        fired.update(report["fired"])
        total = report["cases"]
    assert len(fired) == total, sorted(fired)


def test_every_rule_the_loader_can_emit_is_documented_in_schema_md(tmp_path):
    # The refusal panel tells the reader "See SCHEMA.md for the rule numbers",
    # so a rule id that fires but is undocumented sends the reader nowhere.
    out = _run_core(
        """
        console.log(JSON.stringify(Array.from(new Set(ATLAS.CORRUPTIONS.map(c => c.rule))).sort()));
        """,
        tmp_path,
    )
    rules = json.loads(out)
    html = _html()
    emitted = set(re.findall(r'[EW]\("(R\d+)"', html))
    assert emitted <= set(rules), sorted(emitted - set(rules))
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    documented = set(re.findall(r"^\| (\d+) \|", schema, re.MULTILINE))
    missing = sorted(int(r[1:]) for r in emitted if r[1:] not in documented)
    assert not missing, "rules missing from SCHEMA.md: %s" % missing


def test_schema_md_states_the_self_tests_real_case_count(tmp_path):
    """WAVE C AUDIT: SCHEMA.md said 34 cases while the harness ran 37.

    SCHEMA.md is the frozen fws_atlas/1 contract and the copy a reader trusts,
    and the rule-coverage test above never checked the COUNT -- only that each
    rule id appears in the table. This asserts the integer in the prose equals
    what selfTest actually returns, so the sentence cannot rot again.
    """
    out = _run_core("console.log(ATLAS.selfTest(doc).length);", tmp_path)
    rows = int(out)
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    stated = re.search(r"It runs (\d+)\s*\ncases:", schema)
    assert stated, "SCHEMA.md no longer states a self-test case count"
    assert int(stated.group(1)) == rows


@pytest.mark.parametrize(
    "rule,field,mutation",
    [
        ("R1", "provenance", "delete d.provenance;"),
        ("R24", "cards.ctt_4k_1024x4.slicing", "d.cards.ctt_4k_1024x4.slicing = true;"),
        ("R25", "slice", "d.tiles[0].slice = {index: 9, of: 2, bits: 4};"),
        ("R26", "role", 'd.systems[0].role = "mixed";'),
        ("R27", "duty_cycle", "d.macros[0].duty_cycle = 5.0;"),
        ("R6", "basis", 'd.links[0].basis = "";'),
        # The `svc` role is DOCUMENTED and ACCEPTED (see the svc test below);
        # an undocumented role still refuses, so widening the list did not
        # turn R6 into a rubber stamp.
        ("R6", "role", 'd.links[0].role = "wire";'),
        ("R18", "value", 'd.metrics[0].value = "lots";'),
    ],
)
def test_declared_schema_rules_are_enforced_not_just_documented(rule, field, mutation, tmp_path):
    out = _run_core(
        """
        const d = JSON.parse(JSON.stringify(doc));
        %s
        const v = ATLAS.validate(d);
        console.log(JSON.stringify(v.errors.map(e => e.rule + ' ' + e.field)));
        """
        % mutation,
        tmp_path,
    )
    hits = [e for e in json.loads(out) if e.startswith(rule + " ") and field in e]
    assert hits, json.loads(out)


def test_the_svc_role_is_accepted_by_the_loader_and_documented(tmp_path):
    """NEW GATE: role `svc` loads clean, draws its own dash, and is in SCHEMA.md.

    A role the exporter emits and the viewer rejects is a broken page, and a
    role the viewer accepts and SCHEMA.md never mentions is an undocumented
    field. Both halves are pinned here, in the loader's own words.
    """
    out = _run_core(
        """
        const d = JSON.parse(JSON.stringify(doc));
        d.links[0].role = "svc";
        const v = ATLAS.validate(d);
        console.log(JSON.stringify(v.errors.map(e => e.rule + ' ' + e.field)));
        """,
        tmp_path,
    )
    assert [e for e in json.loads(out) if e.startswith("R6 ") and "role" in e] == []
    html = _html()
    # Its own dash pattern, so it is distinguishable from `act` on the picture.
    assert 'svc: "4 2 1 2"' in html
    # ... and it is in the legend's role list, so a reader is told it exists.
    assert '["tp", "ep", "pp", "pd", "act", "svc"].filter' in html
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    assert "`svc`" in schema
    assert "shared digital chiplet and each" in schema
    assert "operands out" in schema and "results back" in schema
    assert "PRICED rows" in schema


# --- P5.4 duty cycle, and the PD two-system document (D16) ------------------

def _shipped_documents():
    """Every fws_atlas/1 document in docs/qif/atlas/, found by SCHEMA ID.

    WAVE C AUDIT: this was a hand-maintained tuple, and qwen3_5_4b.json shipped
    into the same directory without being added to it -- so the view-rule sweep
    and the D23 scan below, which both claim to cover "every shipped document",
    silently skipped one. Globbing by the schema id means a document another
    workstream lands is covered the moment it exists, with nobody to remember.
    """
    found = []
    for path in sorted(ATLAS_DIR.glob("*.json")):
        try:
            blob = json.loads(path.read_text(encoding="utf-8"))
        except (ValueError, UnicodeDecodeError):
            continue
        if isinstance(blob, dict) and blob.get("schema") == "fws_atlas/1":
            found.append(path.name)
    return tuple(found)


SHIPPED = _shipped_documents()


def test_the_pd_document_is_a_two_system_machine_with_one_handoff():
    """D16 drawn: two inventories, two roles, one priced handoff between them."""
    assert PD_ATLAS.exists(), (
        "docs/qif/atlas/pd_llama7b.json is the P5.4 PD artifact and is committed; "
        "regenerate it with the command in its provenance block"
    )
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    assert doc["schema"] == "fws_atlas/1"
    assert [system["role"] for system in doc["systems"]] == ["prefill", "decode"]
    assert [system["phase"] for system in doc["systems"]] == ["prefill", "decode"]
    chip_system = {chip["id"]: chip["system"] for chip in doc["chips"]}
    handoff = [link for link in doc["links"] if link["role"] == "pd"]
    assert len(handoff) == 1
    assert chip_system[handoff[0]["from"]] != chip_system[handoff[0]["to"]]
    assert handoff[0]["bytes"] > 0 and handoff[0]["per"] and handoff[0]["basis"]
    # Two INVENTORIES, not two halves of one: each system holds its own chips.
    for system in doc["systems"]:
        assert any(chip["system"] == system["id"] for chip in doc["chips"])


def test_the_pd_document_prices_each_half_on_its_own_timeline():
    """P4 duty cycles and metrics per SYSTEM (P5.4). One evaluation shared
    between the halves would print a single measurement twice."""
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    chip_system = {chip["id"]: chip["system"] for chip in doc["chips"]}
    duty = {"sys.prefill": [], "sys.decode": []}
    for macro in doc["macros"]:
        value = macro.get("duty_cycle")
        if value is not None:
            duty[chip_system[macro["chip"]]].append(value)
    assert duty["sys.prefill"] and duty["sys.decode"]
    assert all(0.0 <= v <= 1.0 for values in duty.values() for v in values)
    # The two timelines are different machines, so their duty cycles differ.
    assert max(duty["sys.prefill"]) != max(duty["sys.decode"])
    keys = [metric["key"] for metric in doc["metrics"]]
    assert any(key.startswith("sys.prefill.") for key in keys)
    assert any(key.startswith("sys.decode.") for key in keys)
    # The headline label is published twice — once per system — which is exactly
    # why R28 requires every metric to name its system.
    headline = [m for m in doc["metrics"] if m["key"].endswith(".tokens_per_s")]
    assert len(headline) == 2
    assert headline[0]["label"] == headline[1]["label"]
    assert headline[0]["key"] != headline[1]["key"]


def test_the_pd_document_discloses_what_two_inventories_mean():
    """The two facts a PD reader cannot infer from the picture (D21)."""
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    by_key = {item["constraint"]: item for item in doc["relaxations"]}
    assert "pd_each_half_maps_the_whole_model" in by_key
    assert "pd_each_half_prices_the_whole_request" in by_key
    # One entry per constraint key, even though two systems disclose them.
    keys = [item["constraint"] for item in doc["relaxations"]]
    assert len(keys) == len(set(keys)), keys
    # A constraint the halves disclose DIFFERENTLY names both of them rather
    # than silently keeping one.
    window = by_key["decode_series_window"]["value"]
    assert "sys.prefill" in window and "sys.decode" in window


def test_the_pd_document_validates_clean_through_the_real_loader(tmp_path):
    out = _run_core(
        """
        const v = ATLAS.validate(doc);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          warnings: v.warnings.map(w => w.rule + ' ' + w.field),
        }));
        """,
        tmp_path,
        document=PD_ATLAS,
    )
    report = json.loads(out)
    assert report["errors"] == []
    assert report["warnings"] == []


def test_the_pd_document_is_what_a_fresh_run_produces(tmp_path):
    """Regenerate and compare BYTES: a stale artifact is a wrong picture under
    a right title, the same gate p3_llama7b_tp2.json and the Granite atlas have."""
    import tools.fws_emit_atlas as emit
    import fws_atlas_export

    _pair, _rows, document = emit.build_pd(**PD_ARGS)
    regenerated = fws_atlas_export.write_atlas_json(document, tmp_path / "pd.json")
    assert regenerated == PD_ATLAS.read_text(encoding="utf-8"), (
        "docs/qif/atlas/pd_llama7b.json is stale; regenerate it with the command "
        "in its provenance block"
    )


def test_the_unpriced_pd_path_builds_a_clean_document_and_claims_less(tmp_path):
    """WAVE C AUDIT: `--pd` without `--priced` is advertised and was untested.

    The module docstring documents the combination and every PD test above sets
    priced=True, so this branch had never been run by the suite. Two things it
    must get right: the document still passes the real loader, and it discloses
    LESS -- an unpriced document lowers no request, so the whole-REQUEST claim
    has nothing to be about and must not appear beside the whole-MODEL one.
    """
    import tools.fws_emit_atlas as emit
    import fws_atlas_export

    args = dict(PD_ARGS)
    args["priced"] = False
    _pair, _rows, document = emit.build_pd(**args)
    path = tmp_path / "pd_unpriced.json"
    fws_atlas_export.write_atlas_json(document, path)

    constraints = {item["constraint"] for item in document["relaxations"]}
    assert "pd_each_half_maps_the_whole_model" in constraints
    assert "pd_each_half_prices_the_whole_request" not in constraints
    assert all(macro.get("duty_cycle") is None for macro in document["macros"])

    out = _run_core(
        """
        const v = ATLAS.validate(doc);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          warnings: v.warnings.map(w => w.rule + ' ' + w.field),
        }));
        """,
        tmp_path,
        document=path,
    )
    report = json.loads(out)
    assert report["errors"] == [] and report["warnings"] == []


def test_the_pd_command_in_the_provenance_block_is_the_one_that_made_it():
    doc = json.loads(PD_ATLAS.read_text(encoding="utf-8"))
    command = doc["provenance"]["reference_run"]["command"]
    assert command.startswith("tools/fws_emit_atlas.py --pd ")
    assert "--priced" in command
    for flag, value in (
        ("--pd_prefill_layers_per_chip", PD_ARGS["prefill_layers_per_chip"]),
        ("--pd_decode_layers_per_chip", PD_ARGS["decode_layers_per_chip"]),
        ("--pd_prefill_shared_chiplets", PD_ARGS["prefill_shared_chiplets"]),
        ("--pd_decode_shared_chiplets", PD_ARGS["decode_shared_chiplets"]),
        ("--pd_decode_window", PD_ARGS["decode_window"]),
    ):
        assert "%s %s" % (flag, value) in command, flag


def test_no_shipped_document_smuggles_an_accuracy_field(tmp_path):
    # D23 is hard, and it applies to every artifact in this directory.
    banned = ("accuracy", "perplexity", "top1", "top_1", "bleu", "error_rate")
    for name in SHIPPED:
        blob = (ATLAS_DIR / name).read_text(encoding="utf-8").lower()
        for word in banned:
            assert word not in blob, (name, word)


# --- P5.4 / P5.5 the view rules ---------------------------------------------


@pytest.mark.parametrize("name", SHIPPED)
def test_the_view_rules_hold_on_every_shipped_document(name, tmp_path):
    """The renderer's own encoding law, asserted document by document."""
    out = _run_core(
        """
        const rows = ATLAS.viewTest(doc);
        console.log(JSON.stringify({
          total: rows.length,
          broken: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what + ' :: ' + r.got),
        }));
        """,
        tmp_path,
        document=ATLAS_DIR / name,
    )
    report = json.loads(out)
    assert report["broken"] == []
    assert report["total"] >= 9


def test_every_view_rule_the_renderer_asserts_is_documented_in_schema_md(tmp_path):
    # The same gate the refusals have: a rule the panel prints and SCHEMA.md
    # does not carry sends the reader nowhere.
    out = _run_core(
        """
        console.log(JSON.stringify(ATLAS.viewTest(doc).map(r => r.rule)));
        """,
        tmp_path,
    )
    rules = json.loads(out)
    assert len(rules) == len(set(rules)), rules
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    documented = set(re.findall(r"^\| (V\d+) \|", schema, re.MULTILINE))
    assert set(rules) <= documented, sorted(set(rules) - documented)


def test_the_duty_channel_is_its_own_ink_and_never_a_group_hue(tmp_path):
    out = _run_core(
        """
        console.log(JSON.stringify({
          duty: ATLAS.DUTY_INK,
          hues: ATLAS.HUES,
          extreme: ATLAS.dutyExtreme(doc),
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["duty"] not in report["hues"]
    # The fixture declares duty cycles, so the legend has a busiest macro to name.
    assert report["extreme"] and 0.0 <= report["extreme"]["value"] <= 1.0


def test_a_filter_changes_the_picture_and_never_a_figure(tmp_path):
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        const before = JSON.stringify({m: doc.metrics, h: ATLAS.hueMap(doc)});
        const f = ATLAS.emptyFilter();
        f.q = 'lm_head';
        const selected = doc.macros.filter(m => ATLAS.macroMatches(doc, ix, m, f)).length;
        const after = JSON.stringify({m: doc.metrics, h: ATLAS.hueMap(doc)});
        console.log(JSON.stringify({same: before === after, selected: selected, all: doc.macros.length}));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["same"], "a filter moved a metric or repainted a group"
    assert 0 < report["selected"] < report["all"], report


def test_owner_search_indexes_owners_and_not_measurements(tmp_path):
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        const measured = doc.macros.find(m => typeof m.duty_cycle === 'number' && String(m.duty_cycle).indexOf('.') > 0);
        const byValue = ATLAS.emptyFilter(); byValue.q = String(measured.duty_cycle);
        const byOwner = ATLAS.emptyFilter(); byOwner.q = doc.tiles[0].owner.block;
        console.log(JSON.stringify({
          needle: String(measured.duty_cycle),
          byValue: doc.macros.filter(m => ATLAS.macroMatches(doc, ix, m, byValue)).length,
          byOwner: doc.macros.filter(m => ATLAS.macroMatches(doc, ix, m, byOwner)).length,
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["byValue"] == 0, report
    assert report["byOwner"] > 0, report


def test_a_column_map_bracket_never_spans_two_weight_matrices(tmp_path):
    """D11: a bit-sliced group shares a bracket — and shares it with nothing else."""
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        let brackets = 0, chained = 0, bad = [];
        doc.macros.forEach(m => {
          ATLAS.bracketsFor(doc, ix, m).forEach(b => {
            brackets++;
            if (b.chained.length) chained++;
            const owners = new Set(b.tiles.map(id => ATLAS.ownerKey(ix.tile[id])));
            if (owners.size !== 1) bad.push(m.id + ' ' + b.key);
            b.tiles.forEach(id => {
              const t = ix.tile[id];
              if (t.columns.start < b.start || t.columns.start + t.columns.count > b.end) {
                bad.push(m.id + ' span ' + id);
              }
              if (b.chained.indexOf(t.macro) >= 0) bad.push(m.id + ' chained-to-itself');
            });
          });
        });
        console.log(JSON.stringify({brackets: brackets, chained: chained, bad: bad.slice(0, 5)}));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["bad"] == []
    assert report["brackets"] > 0
    # The fixture's weight matrices chain across macros, which is the D11
    # question the column map exists to answer.
    assert report["chained"] > 0


def test_breadcrumbs_are_containment_and_the_draw_budget_is_applied(tmp_path):
    out = _run_core(
        """
        const ix = ATLAS.makeIndex(doc);
        const macro = doc.macros.find(m => (m.tiles || []).length);
        const path = ATLAS.crumbs(doc, ix, 'macro', null, macro.id);
        const fat = JSON.parse(JSON.stringify(doc.chips[0]));
        for (let i = 0; i <= ATLAS.DRAW_BUDGET; i++) fat.macros.push('ghost.mac.' + i);
        fat.capacity.macro_slots = fat.macros.length;
        const real = ix.chip[macro.chip];   // a chip that actually holds tiles
        console.log(JSON.stringify({
          levels: path.map(c => c.level),
          chip: path[1].id === macro.chip,
          system: ix.chip[macro.chip].system === ix.sys[ix.chip[macro.chip].system].id,
          budget: ATLAS.DRAW_BUDGET,
          fatDrawn: ATLAS.chipDrawable(doc, fat),
          realDrawn: doc.chips.every(c => ATLAS.chipDrawable(doc, c)),
          slots: (real.capacity || {}).macro_slots,
          rectsDuty: ATLAS.chipRects(doc, real, true),
          rectsPlain: ATLAS.chipRects(doc, real, false),
          pkg: ATLAS.drawnRects(doc, 'package', null, null, false),
          chips: doc.chips.length,
          macroRects: ATLAS.macroRects(macro, false),
          tiles: (macro.tiles || []).length,
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["levels"] == ["package", "chip", "macro"]
    assert report["chip"] and report["system"]
    assert report["budget"] == 10000
    assert report["fatDrawn"] is False and report["realDrawn"] is True
    # WAVE C AUDIT: the budget is stated in RECTS, so it must be COUNTED in
    # rects. It used to be enforced against capacity.macro_slots, which is a
    # different and much smaller quantity -- a chip that passed the slot check
    # could still emit five times the budget. These assertions pin the unit.
    assert report["rectsDuty"] > report["slots"]
    assert report["rectsPlain"] > report["slots"]
    assert report["rectsDuty"] == report["rectsPlain"] + 2 * report["slots"]
    assert report["pkg"] > report["chips"]          # a chip is not one rect
    assert report["macroRects"] == report["tiles"] + 1  # the track plus a band each


def test_every_metric_in_the_pd_document_names_its_system(tmp_path):
    out = _run_core(
        """
        const named = doc.metrics.map(m => ATLAS.metricSystem(doc, m));
        console.log(JSON.stringify({
          orphans: doc.metrics.filter((m, i) => named[i] == null).map(m => m.key),
          systems: Array.from(new Set(named)).sort(),
        }));
        """,
        tmp_path,
        document=PD_ATLAS,
    )
    report = json.loads(out)
    assert report["orphans"] == []
    assert report["systems"] == ["sys.decode", "sys.prefill"]


def test_schema_md_documents_the_contract_the_renderer_now_reads():
    """The Wave B audit caught SCHEMA.md omitting fields the renderer used.

    Every field, channel and query parameter added in P5.4/P5.5 is named here,
    so the contract and the page cannot drift apart again.
    """
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    for token in (
        "`system` | string",          # metrics[].system
        "`duty_cycle` | number \\| null",
        "?data=<file>",
        "?duty=1",
        "?view=package",
        "`?macro=<macro id>`",
        "Bar on the macro's top edge",
        "Bracket over a column span",
        "Dimming",
        "pd_llama7b.json",
        "absolute 0–1 scale",
    ):
        assert token in schema, token


def test_the_page_fetches_its_artifacts_and_a_deep_link_still_opens_one_document():
    """The boot block is the one part of the page no headless run reaches.

    It touches location, document, fetch and the live state object, so this is
    a SOURCE-level assertion. The page is the results page: it fetches the
    model's own three artifacts, and ?data=<file> still opens a single document
    on its own (the drilldown alone) rather than being ignored.
    """
    html = _html()
    assert 'rsFetch(id + "_report.json")' in html
    assert 'rsFetch("../dse/" + id + "_frontier/dse_report.json")' in html
    assert 'rsFetch(id + ".json")' in html
    # ?data= keeps the one-document deep link, and it turns the results layer off.
    assert 'var wanted = param("data");' in html
    assert "RS.solo = true;" in html
    # No hardcoded fixture is opened by default any more.
    assert 'fixture_llama7b_tp2.json' not in html
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    assert "the sibling fetch runs only when this parameter asks for one" in schema

def test_the_quotient_scan_covers_every_placement_table():
    """R9 reads the placement tables too, not just the document root.

    A half-ported area-division producer would put per-chip arithmetic exactly
    there, and the self-test proves it by corrupting a macros[] row.
    """
    html = _html()
    assert '["macros", "tiles", "links", "metrics"].forEach(function (k) {' in html
    assert "d.macros[0].arrays_per_chip = 3.7" in html


def test_a_bit_sliced_group_shares_one_bracket(tmp_path):
    """D11's own sentence, drawn: no shipped card slices today, so the case is
    built on a copy of the fixture — two tiles of ONE weight matrix on ONE
    macro, each carrying a slice role."""
    out = _run_core(
        """
        const d = JSON.parse(JSON.stringify(doc));
        const macro = d.macros.find(m => (m.tiles || []).length >= 2);
        const card = d.cards[macro.card];
        card.bits_per_cell = 4;
        card.slicing = true;                       // 4 < weight_bits, ADJ-4
        const tiles = macro.tiles.map(id => d.tiles.find(t => t.id === id));
        tiles[1].owner = JSON.parse(JSON.stringify(tiles[0].owner));
        tiles.forEach((t, i) => { t.slice = {index: i, of: tiles.length, bits: 4}; });
        const v = ATLAS.validate(d);
        const ix = ATLAS.makeIndex(d);
        const brackets = ATLAS.bracketsFor(d, ix, macro);
        const mine = brackets.filter(b => b.tiles.length === tiles.length);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          kinds: brackets.map(b => b.kind),
          label: mine.length ? mine[0].label : null,
          owners: mine.length ? Array.from(new Set(mine[0].tiles.map(id => ATLAS.ownerKey(ix.tile[id])))).length : 0,
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["errors"] == [], report["errors"]
    assert "slice" in report["kinds"]
    assert "bit slices (D11)" in report["label"]
    assert report["owners"] == 1


# --- P7.6 the folding views: the folding card, the time lanes, the frontier ---

FOLD_FIXTURE = ATLAS_DIR / "fixture_granite_folding.json"
FRONTIER_FIXTURE = ATLAS_DIR / "fixture_frontier_granite.json"
GRANITE_ATLAS = ATLAS_DIR / "granite_4_0_h_tiny.json"
FRONT_EMBED_RE = re.compile(
    r'<script[^>]*type="application/json"[^>]*id="frontier-embedded"[^>]*>(.*?)</script>',
    re.DOTALL,
)
# The eight excerpt macro slots the folding fixture copies out of the shipped
# Granite atlas, and the tiles they hold.
EXCERPT_MACROS = tuple("sys.fws.mac.%06d" % i for i in range(8))


def _fold() -> dict:
    return json.loads(FOLD_FIXTURE.read_text(encoding="utf-8"))


def _frontier() -> dict:
    return json.loads(FRONTIER_FIXTURE.read_text(encoding="utf-8"))


def _run_core_pair(driver: str, tmp_path: Path, document: Path, frontier: Path) -> str:
    """Evaluate the core with BOTH kinds of document in scope.

    An atlas and a frontier are two documents, so the driver gets two globals:
    ``doc`` (fws_atlas/1) and ``front`` (fws_frontier/1).
    """
    html = _html()
    core = html[html.index(CORE_START) : html.index(CORE_END)]
    script = tmp_path / "driver_pair.js"
    script.write_text(
        "const fs = require('fs');\n"
        "const doc = JSON.parse(fs.readFileSync(%r, 'utf8'));\n" % str(document)
        + "const front = JSON.parse(fs.readFileSync(%r, 'utf8'));\n" % str(frontier)
        + "const ATLAS = eval('(function(){' + "
        + json.dumps(core)
        + " + '; return ATLAS; })()');\n"
        + textwrap.dedent(driver),
        encoding="utf-8",
    )
    result = subprocess.run(
        [_node(), str(script)], capture_output=True, text=True, timeout=120, cwd=str(PROJECT_ROOT)
    )
    assert result.returncode == 0, result.stderr
    return result.stdout.strip()


def test_the_folding_fixture_copies_the_real_granite_rows_verbatim():
    """The anti-staleness gate a HAND fixture can have.

    The generated documents are pinned by regenerate-and-compare. This one is
    hand-authored, so what is pinned instead is its provenance claim: the
    placement rows are copied from the shipped Granite artifact ROW FOR ROW. If
    the source artifact is regenerated and moves, this fails — which is the
    same protection, applied to the half of the file that is not invented.
    """
    fold, src = _fold(), json.loads(GRANITE_ATLAS.read_text(encoding="utf-8"))
    src_macros = {m["id"]: m for m in src["macros"]}
    src_tiles = {t["id"]: t for t in src["tiles"]}
    fold_macros = {m["id"]: m for m in fold["macros"]}
    assert fold["cards"] == src["cards"]
    for mid in EXCERPT_MACROS:
        assert mid in fold_macros, mid
        assert fold_macros[mid] == src_macros[mid], mid
    for tile in fold["tiles"]:
        assert tile == src_tiles[tile["id"]], tile["id"]
    # The excerpt chip is a real chip with a stated, smaller slot count.
    chip = [c for c in fold["chips"] if c["pool"] == "analog"][0]
    assert chip["macros"] == list(EXCERPT_MACROS)
    assert chip["capacity"]["macro_slots"] == len(EXCERPT_MACROS)
    assert any(r["constraint"] == "excerpt_is_not_the_run" for r in fold["relaxations"])


def test_the_folding_fixture_validates_clean_and_reports_its_idle_banks(tmp_path):
    """Clean through BOTH loaders, with the one honest warning it must carry.

    Six banks of the real Granite excerpt fire on no pass — the 304-column
    ssm_in_proj remainder and the 64-column router each leave three banks dark.
    Under Invariant W that is waste, and T9 reports it rather than refusing it
    (D27 makes waste a metric, not an error).
    """
    out = _run_core(
        """
        const base = ATLAS.validate(doc);
        const ext = ATLAS.validateExt(doc);
        console.log(JSON.stringify({
          baseErrors: base.errors.map(e => e.rule + ' ' + e.field),
          baseWarnings: base.warnings.map(w => w.rule + ' ' + w.field),
          extErrors: ext.errors.map(e => e.rule + ' ' + e.field),
          extWarnings: ext.warnings.map(w => w.rule + ' ' + w.field),
        }));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
    )
    report = json.loads(out)
    assert report["baseErrors"] == [] and report["baseWarnings"] == []
    assert report["extErrors"] == []
    idle = report["extWarnings"]
    assert len(idle) == 6, idle
    assert all(entry.startswith("T9 ") for entry in idle)
    assert sum("mac.000004" in entry for entry in idle) == 3
    assert sum("mac.000007" in entry for entry in idle) == 3


def test_the_folding_extension_self_test_fires_every_refusal(tmp_path):
    out = _run_core(
        """
        const rows = ATLAS.extSelfTest(doc);
        console.log(JSON.stringify({
          total: rows.length,
          cases: ATLAS.EXT_CORRUPTIONS.length,
          failed: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what + ' :: ' + r.got),
          skipped: rows.filter(r => r.skipped).map(r => r.rule),
        }));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
    )
    report = json.loads(out)
    assert report["failed"] == []
    assert report["skipped"] == []
    assert report["total"] == report["cases"] + 1


def test_the_folding_refusals_are_all_n_a_on_a_document_without_the_blocks(tmp_path):
    """A document with no folding block is judged by none of these rules.

    The blocks are OPTIONAL, so every shipped atlas that predates P7.6 must
    still load clean; and the honest report for a rule with nothing to corrupt
    is n/a, exactly as the PD rules are on the one-system fixture.
    """
    out = _run_core(
        """
        const rows = ATLAS.extSelfTest(doc);
        const ext = ATLAS.validateExt(doc);
        console.log(JSON.stringify({
          skipped: rows.filter(r => r.skipped).length,
          cases: ATLAS.EXT_CORRUPTIONS.length,
          errors: ext.errors.length,
          warnings: ext.warnings.length,
        }));
        """,
        tmp_path,
    )
    report = json.loads(out)
    assert report["skipped"] == report["cases"]
    assert report["errors"] == 0 and report["warnings"] == 0


def test_the_doa_register_binds_in_code_and_in_the_artifact(tmp_path):
    """D26: a dead fold is refused BY NAME, in the loader and in the document.

    Two halves. The loader carries the register and refuses any variant that
    claims one of its folds; and the artifact must CARRY the register, so an
    exporter cannot ship a folding card that quietly forgets one entry.
    """
    out = _run_core(
        """
        const doa = ATLAS.DOA_FOLDS;
        const named = doc.folding.refused.map(r => r.fold);
        const dropped = JSON.parse(JSON.stringify(doc));
        dropped.folding.refused = dropped.folding.refused.filter(r => r.fold !== 'replication');
        const claimed = JSON.parse(JSON.stringify(doc));
        claimed.folding.cards[0].variants[0].kind = 'prefill_folding';
        console.log(JSON.stringify({
          doa: doa,
          named: named,
          dropped: ATLAS.validateFold(dropped).errors.map(e => e.rule + ' ' + e.field),
          claimed: ATLAS.validateFold(claimed).errors.map(e => e.rule + ' ' + e.message),
          live: ATLAS.FOLD_KINDS,
          kinds: doc.folding.cards.map(c => c.variants.map(v => v.kind)),
        }));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
    )
    report = json.loads(out)
    assert sorted(report["doa"]) == sorted([
        "idle_spread", "multi_tenant_fold", "non_canonical_walk", "pipelined_decode_fold",
        "prefill_folding", "replication", "slicing_x_folding",
    ])
    assert sorted(report["named"]) == sorted(report["doa"])
    assert any(entry.startswith("F3 folding.refused") for entry in report["dropped"])
    assert any("prefill_folding" in msg and "DOA" in msg for msg in report["claimed"])
    # Every variant the fixture draws is a LIVE fold.
    for kinds in report["kinds"]:
        for kind in kinds:
            assert kind in report["live"], kind
            assert kind not in report["doa"], kind


def test_the_viewers_doa_register_carries_every_fold_the_code_refuses(tmp_path):
    """D26 binds ONE register, so the two copies of it must not drift.

    cim_timing.DEAD_FOLDS is the register the packer refuses by name (P7.2).
    The viewer carries its own copy because it judges documents, not calls, and
    it also carries the folds the plan lists as address-only. What it may never
    do is spell a dead fold differently or drop one: a fold refused in code and
    admitted by the artifact contract is a fold that comes back through the
    picture.
    """
    import cim_timing

    out = _run_core("console.log(JSON.stringify(ATLAS.DOA_FOLDS));", tmp_path, document=FOLD_FIXTURE)
    viewer = set(json.loads(out))
    assert set(cim_timing.DEAD_FOLDS) <= viewer, sorted(set(cim_timing.DEAD_FOLDS) - viewer)
    # And the artifact carries the same register, name for name.
    assert {r["fold"] for r in _fold()["folding"]["refused"]} == viewer


def test_a_fold_moves_cells_and_never_changes_how_many_there_are(tmp_path):
    """Invariant W (D27), hand-computed on the real ssm_out_proj of layer 0.

    granite_4_0_h_tiny's ssm_out_proj is d_inner 3072 -> hidden 1536, carried by
    two tiles that share one owner tuple (K = 1536 each). So K x N = 3072 x 1536
    = 4 718 592 cells, and a 1536 x 1536 macro slot holds 2 359 296 of them: the
    floor is exactly 2 slots. Both variants must enumerate that same number and
    cost that same silicon; what differs between them is where the K partials
    meet, which is the whole point of the card.
    """
    out = _run_core(
        """
        const card = doc.folding.cards.find(c => c.id === 'fold.ssm_out_proj.l0');
        const per = card.variants.map(v => {
          let cells = 0, passes = 0;
          v.boxes.forEach(b => ATLAS.passesOfBox(b).forEach(p => {
            if (!ATLAS.sameOwner(p.owner, card.tensor.owner)) return;
            cells += p.rows.count * p.columns.count;
            passes += 1;
          }));
          return {id: v.id, kind: v.kind, cells: cells, passes: passes,
                  area: v.area.value, slots: v.area.slots,
                  where: v.accumulator.where, bytes: v.accumulator.transport_bytes,
                  waste: v.waste.cells, energy: v.energy.value};
        });
        console.log(JSON.stringify({K: card.tensor.K, N: card.tensor.N,
          cells: card.tensor.cells, floor: card.floor_macros, per: per}));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
    )
    report = json.loads(out)
    assert (report["K"], report["N"]) == (3072, 1536)
    assert report["cells"] == 3072 * 1536 == 4718592
    assert report["floor"] == 4718592 // (1536 * 1536) == 2
    variants = {v["id"]: v for v in report["per"]}
    assert set(variants) == {"v.k_spread", "v.k_stack"}
    for variant in variants.values():
        assert variant["cells"] == 4718592
        assert variant["slots"] == 2
        assert variant["area"] == pytest.approx(2 * 2.0204136)
        assert variant["passes"] == 8          # 2 macros x 4 mux banks, once per step
        assert variant["waste"] == 0
        assert variant["energy"] is None       # no card law prices a reduction
    # The one real difference: where the partials meet, and what crosses.
    assert variants["v.k_spread"]["where"] == "cross_macro"
    assert variants["v.k_spread"]["bytes"] == 12288.0   # N 1536 x batch 4 x 2 B
    assert variants["v.k_stack"]["where"] == "in_macro"
    assert variants["v.k_stack"]["bytes"] == 0.0


def test_the_waste_card_counts_cells_and_not_columns(tmp_path):
    """D27, hand-computed on the real router of layer 0.

    The router is 1536 x 64 and today owns a whole 1536 x 1536 slot, so
    (1536 - 64) x 1536 = 2 260 992 cells are unheld: 95.8333% of the slot. The
    atlas's own macros[].occupancy prints 0.0417 for the same macro and measures
    COLUMNS. The dense variant shares one 384-column bank with ssm_in_proj's
    real 304-column remainder: 64 + 304 = 368, leaving a 16-column remainder,
    16 x 1536 = 24 576 cells, 4.1667% of the bank. That remainder is the only
    waste Invariant W admits.
    """
    out = _run_core(
        """
        const card = doc.folding.cards.find(c => c.id === 'fold.router.l0');
        const macro = doc.macros.find(m => m.id === 'sys.fws.mac.000007');
        console.log(JSON.stringify({
          K: card.tensor.K, N: card.tensor.N, cells: card.tensor.cells,
          occupancy: macro.occupancy,
          variants: card.variants.map(v => ({
            id: v.id, kind: v.kind, waste: v.waste, area: v.area.value,
            kindOfArea: v.area.basis_kind, passes: v.time.passes,
          })),
        }));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
    )
    report = json.loads(out)
    assert (report["K"], report["N"], report["cells"]) == (1536, 64, 98304)
    assert report["occupancy"] == pytest.approx(64 / 1536)
    placed, dense = report["variants"]
    assert placed["kind"] == "n_spread" and dense["kind"] == "dense_share"
    assert placed["waste"]["cells"] == (1536 - 64) * 1536 == 2260992
    assert placed["waste"]["pct"] == pytest.approx(2260992 / (1536 * 1536) * 100)
    assert placed["waste"]["pct"] == pytest.approx(95.83333333)
    assert placed["kindOfArea"] == "slots"
    assert placed["area"] == pytest.approx(2.0204136)
    # P7.2's own itemization: waste = remainder (inside a committed bank) + tail
    # (banks the stream never reached), and there is no third term.
    assert placed["waste"]["terms"] == {
        "remainder_cells": (384 - 64) * 1536,
        "tail_cells": 3 * 384 * 1536,
    }
    assert sum(placed["waste"]["terms"].values()) == placed["waste"]["cells"]
    assert dense["waste"]["cells"] == 16 * 1536 == 24576
    assert dense["waste"]["terms"] == {"remainder_cells": 24576, "tail_cells": 0}
    assert dense["waste"]["pct"] == pytest.approx(16 / 384 * 100)
    assert dense["kindOfArea"] == "cell_share"
    assert dense["area"] == pytest.approx(98304 / (1536 * 1536) * 2.0204136)
    # The tensor's own time does not change: a co-tenant pays its own pass.
    assert placed["passes"] == dense["passes"] == 1


def test_the_time_lane_view_draws_every_bank_of_every_macro(tmp_path):
    """The decode schedule of the excerpt, counted by hand.

    Eight macros x 4 mux banks = 32 lanes. ssm_in_proj fills 4 + 4 + 4 + 4 + 1
    of them (its last N block is 304 of 384 columns), ssm_out_proj 4 + 4, the
    router 1: 26 passes. The other 6 banks fire on nothing, and they are drawn
    anyway — a bank omitted is waste made invisible (D27).
    """
    out = _run_core(
        """
        const boxes = doc.passes.boxes;
        let lanes = 0, passes = 0, idle = 0;
        const byOwner = {};
        boxes.forEach(b => (b.lanes || []).forEach(l => {
          lanes += 1;
          if (!l.passes.length) idle += 1;
          l.passes.forEach(p => {
            passes += 1;
            byOwner[p.owner.block] = (byOwner[p.owner.block] || 0) + 1;
          });
        }));
        console.log(JSON.stringify({
          phase: doc.passes.phase, boxes: boxes.length, lanes: lanes,
          passes: passes, idle: idle, byOwner: byOwner,
          declared: boxes.reduce((n, b) => n + b.passes, 0),
        }));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
    )
    report = json.loads(out)
    assert report["phase"] == "decode"          # D25
    assert report["boxes"] == 8
    assert report["lanes"] == 8 * 4 == 32
    assert report["passes"] == report["declared"] == 26
    assert report["idle"] == 32 - 26 == 6
    assert report["byOwner"] == {"ssm_in_proj": 17, "ssm_out_proj": 8, "router": 1}


def test_the_frontier_fixture_validates_clean_and_fires_every_refusal(tmp_path):
    out = _run_core_pair(
        """
        const v = ATLAS.validateFrontier(front);
        const rows = ATLAS.frontierSelfTest(front);
        const views = ATLAS.frontierViewTest(front);
        console.log(JSON.stringify({
          errors: v.errors.map(e => e.rule + ' ' + e.field),
          total: rows.length, cases: ATLAS.FRONTIER_CORRUPTIONS.length,
          failed: rows.filter(r => !r.pass).map(r => r.rule + ' ' + r.what + ' :: ' + r.got),
          skipped: rows.filter(r => r.skipped).length,
          views: views.map(r => r.rule + (r.pass ? '' : ' BROKEN')),
        }));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
        frontier=FRONTIER_FIXTURE,
    )
    report = json.loads(out)
    assert report["errors"] == []
    assert report["failed"] == [] and report["skipped"] == 0
    assert report["total"] == report["cases"] + 1
    assert report["views"] == ["V12", "V13"]


def test_the_frontier_refuses_a_safety_margin_under_any_of_its_names(tmp_path):
    """D28 is hard: there are no safety margins, so the loader refuses the word.

    A margin is exactly the kind of number that would look innocent in a sweep
    output and quietly move every point, which is why it is refused by NAME
    rather than by value.
    """
    out = _run_core_pair(
        """
        const names = ['safety_margin', 'derate', 'guard_band', 'timing_margin', 'margin'];
        const hits = names.map(n => {
          const d = JSON.parse(JSON.stringify(front));
          d.points[0][n] = 0.15;
          return ATLAS.validateFrontier(d).errors.filter(e => e.rule === 'X11').length;
        });
        const clean = ATLAS.validateFrontier(front).errors.filter(e => e.rule === 'X11').length;
        console.log(JSON.stringify({hits: hits, clean: clean}));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
        frontier=FRONTIER_FIXTURE,
    )
    report = json.loads(out)
    assert report["hits"] == [1, 1, 1, 1, 1]
    assert report["clean"] == 0


def test_the_frontier_front_and_knee_are_the_real_sweeps_own_numbers(tmp_path):
    """The nine points are the Wave D candidates, checked against their source.

    The eight swept points are copied from the FROZEN Wave-D sweep at
    docs/qif/dse/granite_lanes_banks_retired (ADJ-9 refuses its axis by name, so
    it can never be regenerated and is labelled as frozen where it lives);
    the ninth is the shipped Granite atlas run. The front is the four
    bank_depth = 1 points (a bank_depth = 2 twin costs the same silicon and runs
    slower, so it is dominated), and the knee is c002, where the digital term of
    the fitted step law first falls below the residual the digital knob cannot
    move.
    """
    dse = json.loads(
        (PROJECT_ROOT / "docs/qif/dse/granite_lanes_banks_retired/dse_report.json").read_text(encoding="utf-8")
    )
    measured = {}
    for candidate in dse["candidates"]:
        entries = {e["key"]: e["value"] for e in candidate["metrics"]["entries"]}
        measured[candidate["id"]] = (
            candidate["knobs"]["vector_lanes"],
            candidate["knobs"]["bank_depth"],
            entries["sys.fws.tokens_per_s"],
            # WAVE F (D29): the sweep is a FILLED PIPELINE, so the per-token
            # period each point publishes is its measured BEAT. The fixture's
            # decode_step_s field carries it — the same quantity, the time from
            # one token to the next, under the schema's existing name.
            entries["sys.fws.beat"],
        )
    front = _frontier()
    points = {p["id"]: p for p in front["points"]}
    silicon = {c["id"]: c["silicon"] for c in dse["candidates"]}
    for pid, (lanes, depth, tokens, step) in measured.items():
        point = points[pid]
        assert point["knobs"]["vector_lanes"] == lanes
        assert point["knobs"]["bank_depth"] == depth
        assert point["throughput"]["tokens_per_s"] == tokens
        assert point["throughput"]["decode_step_s"] == step
        # P7.9: the AREA is checked against its source the same way the
        # throughput is. The document used to carry a two-term sum that was
        # internally consistent and disagreed with the sweep by the whole
        # per-macro pool term, and no gate could see it because no gate
        # compared an area (D21).
        assert point["area"]["total_mm2"] == pytest.approx(
            silicon[pid]["total_silicon_mm2"], rel=1e-12
        )
        assert point["area"]["terms"]["macro_pool_mm2"] == pytest.approx(
            silicon[pid]["macro_pool_silicon_mm2"], rel=1e-12
        )
        assert point["area"]["terms"]["shared_digital_mm2"] == pytest.approx(
            silicon[pid]["shared_digital_silicon_mm2"], rel=1e-12
        )
    # The ninth point is the shipped atlas run, and it is the only clickable one.
    granite = {m["key"]: m["value"] for m in json.loads(GRANITE_ATLAS.read_text(encoding="utf-8"))["metrics"]}
    assert points["ref.atlas"]["throughput"]["tokens_per_s"] == granite["sys.fws.tokens_per_s"]
    assert points["ref.atlas"]["in_sweep"] is False
    # P7.9: the ninth point's engine is DERIVED, and the document says which
    # width and whose it is. It used to be labelled "vector_lanes 1024" — a
    # declared width it does not have, next to a genuinely-declared 1024-lane
    # point with a different area — and to carry 5610 pre-D30 placed tiles.
    report = json.loads(
        (PROJECT_ROOT / "docs/qif/atlas/granite_4_0_h_tiny_report.json").read_text(encoding="utf-8")
    )
    silicon_block = report["evaluation"]["digital_silicon"]
    ref = points["ref.atlas"]
    assert ref["knobs"]["vector_lanes"] == silicon_block["vector_lanes"]
    assert ref["knobs"]["vector_lanes_provenance"] == silicon_block["vector_lanes_provenance"]
    assert "DERIVED" in ref["label"]
    assert ref["provisioning"]["placed_tiles"] == report["mapping"]["tiles"]
    clickable = [p for p in front["points"] if p["atlas"]["exists"]]
    assert [p["id"] for p in clickable] == ["ref.atlas"]
    assert clickable[0]["atlas"]["document"] == GRANITE_ATLAS.name
    assert GRANITE_ATLAS.exists()
    # The declared front, recomputed here from the two axes only.
    def dominated(p):
        return any(
            q is not p
            and q["area"]["total_mm2"] <= p["area"]["total_mm2"]
            and q["throughput"]["tokens_per_s"] >= p["throughput"]["tokens_per_s"]
            and (q["area"]["total_mm2"] < p["area"]["total_mm2"]
                 or q["throughput"]["tokens_per_s"] > p["throughput"]["tokens_per_s"])
            for q in front["points"]
        )
    # ADJ-10 REWRITE, AND IT REVERSES ADJ-9's READING OF THIS PICTURE.
    # Wave F (D31-v1): the front is the four bank_depth = 1 sweep points PLUS
    #   the reference run, because its engine was DERIVED at 220 lanes and
    #   carried less digital silicon than any declared point.
    # ADJ-9 (D31-v2): the derived width is 5479 lanes, WIDER than the widest
    #   declared point, so the reference run cost 39.1 mm2 more than c006 and
    #   measured 56 tokens/s LESS. It was DOMINATED. The cause was named at the
    #   time: the machine was bound by the attention systolic fabric — 18.6 us
    #   on the beat-setting stage against a 1.6 us analog m-pass — which was
    #   DECLARED card geometry no derivation sized, so past the width at which
    #   the scan fits under the attention term, lanes bought area and nothing.
    # ADJ-10 (now): that fabric is DERIVED too — 8 arrays and 12 softmax lanes,
    #   integer copies of measured blocks — the attention term falls to 6.88 us,
    #   and the reference run measures 62661 tokens/s, 2.4x the fastest swept
    #   point, for 131.9 mm2 more silicon than c006. It is BACK ON THE FRONT and
    #   it is now its fastest point. The eight swept points are frozen at the
    #   DECLARED 2-array fabric and can never be re-walked, which is exactly why
    #   the comparison is worth drawing.
    assert sorted(p["id"] for p in front["points"] if p["pareto"]) == [
        "c000", "c002", "c004", "c006", "ref.atlas"
    ]
    ref = [p for p in front["points"] if p["id"] == "ref.atlas"][0]
    c006 = [p for p in front["points"] if p["id"] == "c006"][0]
    assert ref["knobs"]["vector_lanes"] > c006["knobs"]["vector_lanes"]
    assert ref["area"]["total_mm2"] > c006["area"]["total_mm2"]
    assert ref["throughput"]["tokens_per_s"] > 2.4 * c006["throughput"]["tokens_per_s"]
    assert ref["pareto"] is True
    # The reference point is the only one on this picture whose fabric is
    # DERIVED; the eight swept points all ran the declared 2-array geometry.
    assert ref["knobs"]["num_arrays"] == 8
    assert ref["knobs"]["num_arrays_provenance"] == "derived-count"
    assert all("num_arrays" not in p["knobs"] for p in front["points"] if p["in_sweep"])
    for point in front["points"]:
        assert point["pareto"] == (not dominated(point)), point["id"]
    # THE KNEE, REWRITTEN FOR D29 (Wave F). Under the retired lockstep regime
    # the knee sat at 1024 lanes: the scan engine was the whole critical path
    # of a decode step, so the digital term C / lanes was still ABOVE the
    # residual at 512. In the filled pipeline every stage fires every beat, the
    # scan is one stage's work inside a beat, and the digital term is already
    # below the residual at the smallest width the sweep contains — so the knee
    # is the first swept point and every doubling past it pays area for a term
    # that was never binding. The law itself is unchanged and still exact.
    beats = {lanes: step for (lanes, depth, _t, step) in measured.values() if depth == 1}
    c = (beats[512] - beats[4096]) / (1 / 512 - 1 / 4096)
    r = beats[512] - c / 512
    for lanes, beat in beats.items():
        # A FIT, not an identity any more: the lockstep step WAS the scan chain
        # and the law was exact to 1e-13; the D29 beat is a MAX over stages, so
        # the reciprocal-in-lanes law describes it to 4e-5 and the fixture's own
        # basis says exactly that.
        assert r + c / lanes == pytest.approx(beat, rel=1e-4)
    assert "a FIT, not an identity" in front["knee"]["basis"]
    knee_lanes = min(lanes for lanes in beats if c / lanes < r)
    assert knee_lanes == 512
    assert c / 512 / r < 1.0
    knee_id = [p["id"] for p in front["points"]
               if p["in_sweep"] and p["knobs"]["bank_depth"] == 1
               and p["knobs"]["vector_lanes"] == knee_lanes][0]
    assert [p["id"] for p in front["points"] if p["knee"]] == [knee_id]
    assert front["knee"]["point"] == knee_id
    # 8x the lanes buys well under 2x the throughput: the finding the fixture
    # exists to draw, and it survived the regime change with a different cause.
    assert 1.0 < beats[512] / beats[4096] < 2.0


def test_every_frontier_point_reports_utilization_and_waste(tmp_path):
    """D28: per-device utilization at every point, and D27: waste at every point.

    An absent measurement is null WITH A REASON — the shared digital chiplet's
    occupancy is emitted by nothing today — and it draws as the unknown hatch.
    A zero would say the silicon was measured and found idle, which is a
    different and much stronger claim.
    """
    front = _frontier()
    classes = [c["id"] for c in front["device_classes"]]
    assert classes == ["analog_macro", "shared_digital_chiplet"]
    for point in front["points"]:
        got = {u["device_class"]: u for u in point["utilization"]}
        assert sorted(got) == sorted(classes), point["id"]
        analog = got["analog_macro"]
        assert 0.0 < analog["value"] < 1.0 and analog["basis"]
        digital = got["shared_digital_chiplet"]
        assert digital["value"] is None and digital["uncovered"]
        assert 0.0 <= point["packing"]["waste_pct"] <= 100.0
        assert point["packing"]["basis"]
    # The analog figure reproduces the shipped atlas's MEASURED duty cycle on
    # the point that IS the shipped atlas run: 4.732818486437201e-07 s of analog
    # activity per macro per step over that run's own decode step.
    granite = json.loads(GRANITE_ATLAS.read_text(encoding="utf-8"))
    duty = max(m["duty_cycle"] for m in granite["macros"] if m["duty_cycle"] is not None)
    ref = [p for p in front["points"] if p["id"] == "ref.atlas"][0]
    analog = [u for u in ref["utilization"] if u["device_class"] == "analog_macro"][0]
    assert analog["value"] == pytest.approx(duty, rel=1e-12)


def test_the_frontier_marks_the_field_no_producer_emits():
    """WAVE F REWRITE (D32, P7.8): the x axis is real, and ONE field is still absent.

    OLD CLAIM: the shared-digital AREA term is an invented placeholder, and the
    fixture wears the mark, because the digital card declared no area_mm2 —
    which is exactly why the Wave D front collapsed to one point. NEW CLAIM: D32
    composes that term from measured synthesis blocks, so nothing in this
    document is invented; what remains marked is what the composition does NOT
    cover (activation SRAM, interconnect, control — no block in the library) and
    the per-candidate shared-digital OCCUPANCY, which no producer emits.
    """
    front = _frontier()
    assert front["provenance"]["invented_fields"] == []
    constraints = {r["constraint"] for r in front["relaxations"]}
    assert "shared_digital_area_is_a_placeholder" not in constraints
    assert "shared_digital_area_is_composed_not_measured_in_situ" in constraints
    assert "shared_digital_utilization_uncovered" in constraints
    # P7.9 REWRITE. OLD: the waste figure is the COLUMN census and D27's cell
    # census "does not exist yet". NEW: the cell census landed with P7.2's dense
    # packer in the same plan, it is nearly twice the column figure, and the
    # document now carries it — what is still relaxed is its SCOPE (one
    # reference mapping's census repeated on every row).
    assert "waste_is_the_column_census" not in constraints
    assert "waste_is_one_reference_mappings_cell_census" in constraints
    # ADJ-9 REWRITE. OLD: the axis is RETIRED (still spellable, labelled).
    # NEW: it is REFUSED BY NAME at parse, so the eight points can never be
    # regenerated and their artifact is frozen. Same place, stronger word.
    assert "the_eight_swept_points_sweep_a_REFUSED_axis" in constraints
    assert "the_eight_swept_points_sweep_a_RETIRED_axis" not in constraints
    refused = [
        r for r in front["relaxations"]
        if r["constraint"] == "the_eight_swept_points_sweep_a_REFUSED_axis"
    ][0]
    assert "granite_lanes_banks_retired" in refused["reason"]
    assert "REFUSES the axis by name" in refused["reason"]
    cells = [
        r for r in front["relaxations"]
        if r["constraint"] == "waste_is_one_reference_mappings_cell_census"
    ][0]
    assert "COLUMN census" in cells["reason"] and "per-point" in cells["reason"]
    assert front["points"][0]["packing"]["basis_kind"] == "cells"
    composed = [
        r for r in front["relaxations"]
        if r["constraint"] == "shared_digital_area_is_composed_not_measured_in_situ"
    ][0]
    assert "LOWER BOUND" in composed["reason"]
    for point in front["points"]:
        assert point["area"]["terms"]["shared_digital_mm2"] > 0
        assert point["area"]["terms"]["analog_mm2"] == pytest.approx(12930.64704)
        # P7.9: THREE terms, not two. The per-macro digital pool is a whole
        # device class and the document used to omit it while declaring
        # uncovered == [] — which made its total disagree with the source
        # sweep's own total_silicon_mm2 by exactly that term (D21).
        assert point["area"]["terms"]["macro_pool_mm2"] > 0
        assert sorted(point["area"]["terms"]) == [
            "analog_mm2", "macro_pool_mm2", "shared_digital_mm2"
        ]
        assert sum(point["area"]["terms"].values()) == pytest.approx(point["area"]["total_mm2"])
        assert point["area"]["uncovered"] == []


def test_the_frontier_fixture_still_parses_even_though_the_page_no_longer_embeds_it():
    # The fixture is frozen data with its own provenance, and the loader still
    # opens it on request (?data=). What changed is that the page does not
    # OPEN on it any more.
    front = _frontier()
    assert front["schema"] == "fws_frontier/1"
    assert front["points"]

def test_the_extension_view_rules_hold_and_are_emitted_only_where_they_apply(tmp_path):
    out = _run_core_pair(
        """
        const withBlocks = ATLAS.viewTest(doc).map(r => r.rule);
        const plain = ATLAS.viewTest(JSON.parse(fs.readFileSync(
          'docs/qif/atlas/fixture_llama7b_tp2.json', 'utf8'))).map(r => r.rule);
        const broken = ATLAS.viewTest(doc).filter(r => !r.pass)
          .concat(ATLAS.frontierViewTest(front).filter(r => !r.pass))
          .map(r => r.rule + ' ' + r.got);
        console.log(JSON.stringify({withBlocks: withBlocks, plain: plain, broken: broken}));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
        frontier=FRONTIER_FIXTURE,
    )
    report = json.loads(out)
    assert report["broken"] == []
    assert report["withBlocks"][-2:] == ["V10", "V11"]
    # A document without the blocks is judged by nine rules, as it always was.
    assert "V10" not in report["plain"] and "V11" not in report["plain"]
    assert len(report["plain"]) == 9


def test_every_extension_rule_is_documented_in_schema_md(tmp_path):
    """The same gate the R rules have: a rule the panel prints and SCHEMA.md
    does not carry sends the reader nowhere."""
    out = _run_core_pair(
        """
        console.log(JSON.stringify({
          ext: Array.from(new Set(ATLAS.EXT_CORRUPTIONS.map(c => c.rule))),
          front: Array.from(new Set(ATLAS.FRONTIER_CORRUPTIONS.map(c => c.rule))),
        }));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
        frontier=FRONTIER_FIXTURE,
    )
    rules = json.loads(out)
    declared = set(rules["ext"]) | set(rules["front"])
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    documented = set(re.findall(r"^\| ([FTX]\d+) \|", schema, re.MULTILINE))
    assert declared <= documented, sorted(declared - documented)
    # And nothing the loader can emit is outside the declared set.
    emitted = set(re.findall(r'[EW]\("([FTX]\d+)"', _html()))
    assert emitted <= declared, sorted(emitted - declared)
    # Every extension VIEW rule is documented too.
    views = set(re.findall(r'row\("(V1[0-3])"', _html()))
    assert views == {"V10", "V11", "V12", "V13"}
    assert views <= set(re.findall(r"^\| (V\d+) \|", schema, re.MULTILINE))


def test_schema_md_states_the_extension_self_tests_real_case_counts(tmp_path):
    """The Wave C audit's lesson, applied to the new suites: the integer in the
    prose is asserted against what the harness actually runs."""
    out = _run_core_pair(
        """
        console.log(JSON.stringify([ATLAS.extSelfTest(doc).length,
                                    ATLAS.frontierSelfTest(front).length,
                                    ATLAS.EXT_CORRUPTIONS.length]));
        """,
        tmp_path,
        document=FOLD_FIXTURE,
        frontier=FRONTIER_FIXTURE,
    )
    ext_rows, front_rows, ext_cases = json.loads(out)
    schema = SCHEMA_MD.read_text(encoding="utf-8")
    stated = re.search(r"folding self-test runs (\d+) cases", schema)
    assert stated and int(stated.group(1)) == ext_rows
    stated_front = re.search(r"frontier self-test\s*\nruns (\d+)", schema)
    assert stated_front and int(stated_front.group(1)) == front_rows
    stated_skip = re.search(r"reports all (\d+) folding cases as `n/a`", schema)
    assert stated_skip and int(stated_skip.group(1)) == ext_cases


def test_a_dropped_frontier_document_still_never_displaces_the_atlas():
    """Two documents of two kinds can be on screen at once.

    A dropped fws_frontier/1 file adds a view; it never replaces the mapping
    the reader is looking at. (The page embeds neither kind now — it fetches —
    so what is pinned here is the drop path.)
    """
    html = _html()
    assert 'if (parsed && parsed.schema === A.FRONTIER_SCHEMA) { adoptFrontier(parsed, file.name); return; }' in html
    assert 'S.front = doc; S.frontSource = source; S.selftest = null; S.view = "frontier";' in html

def test_no_frontier_document_smuggles_an_accuracy_field():
    """D23 applies to every artifact, and the frontier is not an atlas document,
    so the shipped-atlas scan above does not reach it."""
    banned = ("accuracy", "perplexity", "top1", "top_1", "bleu", "error_rate")
    blob = FRONTIER_FIXTURE.read_text(encoding="utf-8").lower()
    for word in banned:
        assert word not in blob, word
